name: 
markdown: kramdown
permalink: /:title

theme: jekyll-theme-tactile







title:             Sg3.ch, 
email:             me@simongasser.com
description:       Anleitungen, Projekte und Gedanken zur Digitalisierung.
author:            sigasser
baseurl:           "/"
url:               "https://sigasser.github.io"

# Social Profiles
twitter_username:  sigasser
github_username:   sigasser

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
