name:
markdown: kramdown
permalink: /:title

theme: jekyll-theme-tactile







title:             Sg3.ch,
email:             me@simongasser.com
description:       Anleitungen, Projekte und Gedanken zur Digitalisierung.
author:            sigasser
baseurl:           "/"
url:               "https://sigasser.github.io"

# Social Profiles
twitter_username:  sigasser
github_username:   sigasser

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Team names, titles and social links
people:
- name: Simon Gasser
  pic: 1
  position: Elektro-Sicherheitsberater
  social:
    - title: twitter
      url: https://twitter.com/sigasser
    - title: email
      url: mailto:simon@simon-gasser.ch
    - title: calendar
      url: https://www.supersaas.de/schedule/simon_gasser_gmbh/Simon_Gasser

- name: Michael Mächler
  pic: 2
  position: Elektro-Sicherheitsberater
  social:
    - title: email
      url: mailto:michael@simon-gasser.ch
    - title: calendar
      url: https://www.supersaas.de/schedule/simon_gasser_gmbh/Michael_Maechler


- name: Rachel Gasser
  pic: 3
  position: Buchhaltung
  social:
    - title: email
      url: mailto:rachel@simon-gasser.ch
