name:
markdown: kramdown
permalink: /:title

theme: jekyll-theme-tactile







title:             erstpruefung.ch,
email:             kurs@simongasser.com
description:       Eine Praxisnahe Anleitung für die Erstprüfung nach NIV Art. 24.
author:            sigasser
baseurl:           "/"
url:               "https://erstpruefung.ch"

# Social Profiles
twitter_username:  sigasser
github_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Team names, titles and social links
people:
- name: Simon Gasser
  pic: 1
  position: Elektro-Sicherheitsberater
  social:
    - title: envelope-o
      url: mailto:simon@simon-gasser.ch
    - title: calendar-check-o
      url: https://www.supersaas.de/schedule/simon_gasser_gmbh/Simon_Gasser

- name: Michael Mächler
  pic: 2
  position: Elektro-Sicherheitsberater
  social:
    - title: envelope-o
      url: mailto:michael@simon-gasser.ch
    - title: calendar-check-o
      url: https://www.supersaas.de/schedule/simon_gasser_gmbh/Michael_Maechler


- name: Rachel Gasser
  pic: 3
  position: Buchhaltung
  social:
    - title: envelope-o
      url: mailto:rachel@simon-gasser.ch
